### ISSUE TITLE
DMTCP multiarch broken out of the box

### ISSUE THREAD

**Issue by aparashk** [dmtcp/dmtcp#458]
I have tried many combinations of Linux distributions (Redhat 5, Ubuntu 12.04, Ubuntu 14.04) and DMTCP versions (2.4.0, 2.4.3, 2.4.5, 2.5.0-rc2) and all fail for me in the same way. When I build a multiarch version checkpointing a 32-bit binary process creates a checkpoint, but restoring that causes a crash (SIGSEGV). The sequence of commands I have been using for establishing this are as follows:

```
./configure --enable-m32
make clean
make
./configure
make clean
make
make M32=1 check
```

Note that the single platform (64-bit) version of DMTCP passes the test:

```
make check
```

without problems.

Here is an example of what I get, on Ubuntu 14.04 LTS 64-bit install, when building from source and running a random 32-bit application under DMTCP:

```
# ./configure --enable-m32
[… lots of output, no errors…]
# make clean
[… lots of output, no errors …]
# make
[… lots of output, no errors …]
# ./configure
[… lots of output, no errors …]
# make clean
[… lots of output, no errors …]
# make
[… lots of output, no errors …]
# bin/dmtcp_launch <i386-program>
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_alloc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_dl.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_ipc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_svipc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_timer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_pid.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_alloc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_dl.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_ipc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_svipc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_timer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_pid.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
program> 
```

The messages are the same with other versions of DMTCP, I have tried 2.4.5 and 2.4.1 as well, thus it is not an issue introduced recently. Since the 32-bit application is running, I can checkpoint it, but any attempt to restore it from a saved checkpoint leads to a bus error:

```
# ./dmtcp_restart_script.sh 
size = 1
Bus error (core dumped)
```

Any clues?

**Comment by rohgarg** [comment]
@aparashk: We believe we have a solution to this problem. Could you please try the patch here: #469?

**Comment by aparashk** [comment]
@rohgarg Thank you for the quick response! I will try and report back.

If I am not mistaken, the proposed patch may fix the bus error upon restart. Do you have any idea about the ld.so errors? These effectively prevent the use of any plugins.

**Comment by gc00** [comment]
Hi Atanas,
    I've been following this thread, and consulting internally.
I know about the bus error for 32-bits on restart, and we believe
we've fixed that now.

    But I don't think I know about this issue of ld.so errors
that prevent the use of plugins.  I didn't notice any reference to
that in the e-mail thread or in github issues.  Could you send
more information or a pointer to what is the issue for ld.so
and plugins?

Thanks very much,
- Gene

----- Original Message -----

**Comment by aparashk** [comment]
@gc00 

Hi Gene,

I am referring to the ld.so errors that occur when I try to load a 32-bit executable on a multiarch version of DMTCP:

```
# bin/dmtcp_launch <i386-program>
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_alloc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_dl.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_ipc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_svipc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_timer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_pid.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_alloc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_dl.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_ipc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_svipc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_timer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/work/dmtcp-2.5.0-rc2/lib/dmtcp/libdmtcp_pid.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
program> 
```

It appears that none of the plugins get loaded because of some 32/64 bits .so mismatch, but I can't be sure.

**Comment by aparashk** [comment]
@rohgarg The #469 patch does not resolve the issue completely. I can now restore a 32-bit version of the standard Python 2.7.12 binary, but not a 32-bit version of a more complex binary -- still getting bus error.

Thanks,
Atanas

**Comment by gc00** [comment]
Hi Atanas,
    I have three questions:
1.  Is there "a 32-bit version of a more complex binary" for some
    open source software that exhibits this restart bug?  If so,
    we can diagnose internally here.  If not, are you in a position
    to give us a temporary guest account where we can observe this bug?
    Or maybe create a VM with the bug?

2.  And I have the same question for the ld.so bug.  Locally, the
    plugins are being loaded in our case.

3.  At least for the restart bug, here is what we're observing that
    causes this bug.  Maybe you can diagnose at your end.
    In the past, the Linux kernel would create a vvar memory region
    covering just one page.  You can observe the vvar region by
    doing:  cat /proc/PID/maps   [where you replace PID by your pid).
        For some reason, on recent kernels, and only for 32-bitx,
    the kernel started using two pages for VVAR, and declared them
    both to be r--p (read-only), even though the second page is not
    actually readable.  This seems to be a bug in recent Linux kernels.
    Our workaround it to read only the first page of vvar, even when
    /proc/*/maps says that there are two readable vvar pages.
        Could you check if you always see two vvar memory pages
    using /proc/*/maps (both in the original process launch, and
    in the restarted process)?  Do you see anything interesting?

Thanks,
- Gene

**Comment by aparashk** [comment]
Hi Gene,

Sorry for the delay in my response.

I spoke too soon: I still see the original problem, reproduced as per my original report, using nothing but the DMTCP source itself. I have tried many combinations of Linux and DMTCP versions, including the master branch, with the VDSO fix, but cannot get the DMTCP regressions pass in 32-bit mode in a multi-arch setup.

I guess one of the giveaways that the VDSO is not the (only) issue is that I had this problem on Redhat5, which is based on a 2.x Linux kernel and would not have the issue you describe above...

@karya0 Has anyone tried to reproduce the original problem before closing this issue? If so, what was the setup?

How can I reopen this issue?


Thanks,
Atanas

**Comment by rohgarg** [comment]
@aparashk: We would be happy to take a look at this, but we can't seem to reproduce this locally. Would it be possible for you to provide us a VM image/guest account/specific instructions to debug this?

**Comment by aparashk** [comment]
@rohgard: I have setup an AWS instance which runs stock Ubuntu 14.04 and demonstrates the problem using the commands:

```
git clone https://github.com/dmtcp/dmtcp.git
cd dmtcp
./configure --enable-m32
make clean
make
./configure
make clean
make
make M32=1 check
```

Please email me for the login details. Thank you!

**Comment by rohgarg** [comment]
@karya0 and I were able to identify the issue: it's the last command in
the instructions: `make M32=1 check`. It messes up the installation.

With a multi-arch build, running `make check` for 32-bit tests
(which, I'm guessing, was the intent behind the command) from the
top-level directory is not fully supported out-of-the-box. One has
to manually cd to the tests subdirectory, and build the tests in a
32-bit mode. So, the correct way to run tests would be as follows:
```bash
$ cd test
$ make M32=1 tests # build the tests in 32-bit mode
$ cd ..
$ make check # run make check from the DMTCP root directory
```
Running `make M32=1 check` from the DMTCP root directory ends up
running `make M32=1` on the main makefile which then overwrites the
binaries and messes up the installation.

For future, I suppose we could add a `make check-32` target for
building and running 32-bit tests in a multi-arch setup.

@aparashk reports that `make check` passes after using the
instructions above. Hence, I'm closing this issue.
